In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, r2_score
from sklearn.metrics import mean_absolute_error
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor

In [2]:
car = pd.read_csv('./car/car.csv')

In [3]:
car

,brand,model,year,price,transmission,mileage,fuelType,mpg,engineSize
0,audi,A1,2017,12500,Manual,15735,Petrol,55.4,1.4
1,audi,A1,2016,11000,Manual,29946,Petrol,55.4,1.4
2,audi,A3,2019,17300,Manual,1998,Petrol,49.6,1.0
3,audi,A1,2016,13900,Automatic,32260,Petrol,58.9,1.4
4,audi,A6,2016,13250,Automatic,76788,Diesel,61.4,2.0
...,...,...,...,...,...,...,...,...,...
57502,vw,Eos,2008,4995,Manual,65000,Diesel,48.0,2.0
57503,vw,Eos,2015,12495,Manual,41850,Diesel,58.9,2.0
57504,vw,Eos,2014,8950,Manual,58000,Diesel,58.9,2.0
57505,vw,Eos,2006,2995,Manual,92640,Diesel,48.0,2.0
57506,vw,Eos,2012,5990,Manual,74000,Diesel,58.9,2.0

In [4]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57507 entries, 0 to 57506
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         57507 non-null  object
 1   model         57507 non-null  object
 2   year          57507 non-null  int64
 3   price         57507 non-null  int64
 4   transmission  57507 non-null  object
 5   mileage       57507 non-null  int64
 6   fuelType      57507 non-null  object
 7   mpg           57507 non-null  float64
 8   engineSize    57507 non-null  float64
dtypes: float64(2), int64(3), object(4)
memory usage: 3.9+ MB

In [50]:
car = pd.get_dummies(car, prefix_sep='_', drop_first=True)
car.head()

,year,price,mileage,mpg,engineSize,brand_bmw,brand_cclass,brand_focus,brand_ford,brand_hyundi,...,model_ Yeti Outdoor,model_ Zafira,model_ Zafira Tourer,model_220,transmission_Manual,transmission_Other,transmission_Semi-Auto,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2017,12500,15735,55.4,1.4,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1,2016,11000,29946,55.4,1.4,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,2019,17300,1998,49.6,1.0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,2016,13900,32260,58.9,1.4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,2016,13250,76788,61.4,2.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [51]:
y = car[['price']].to_numpy()
car = car.drop(columns=['price'])

In [52]:
y

array([[12500],
       [11000],
       [17300],
       ...,
       [ 8950],
       [ 2995],
       [ 5990]], dtype=int64)

In [53]:
car

,year,mileage,mpg,engineSize,brand_bmw,brand_cclass,brand_focus,brand_ford,brand_hyundi,brand_merc,...,model_ Yeti Outdoor,model_ Zafira,model_ Zafira Tourer,model_220,transmission_Manual,transmission_Other,transmission_Semi-Auto,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2017,15735,55.4,1.4,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1,2016,29946,55.4,1.4,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,2019,1998,49.6,1.0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,2016,32260,58.9,1.4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,2016,76788,61.4,2.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57502,2008,65000,48.0,2.0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
57503,2015,41850,58.9,2.0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
57504,2014,58000,58.9,2.0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
57505,2006,92640,48.0,2.0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
57506,2012,74000,58.9,2.0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [69]:
x = car.values
columns = car.columns

scaler = preprocessing.MinMaxScaler()
tmp = scaler.fit_transform(x)
car = pd.DataFrame(tmp)
car.columns = columns

x = car.to_numpy()

In [70]:
# 기본값은 75 : 25 비율
X_train, X_test, y_train, y_test = train_test_split(x, y, train_size = 0.75, random_state=1)

# LightGBM 파라미터

- num_leaves : (31) 하나의 트리가 가질 수 있는 최대 리프 개수
- objective : (regression) 수치예측이면 regression, 이진분류이면 binary

- num_iterations:	100	반복 수행하려는 트리의 개수 (너무 크면 오버피팅 발생)
- objective:	regression	수치예측이면 regression, 이진분류이면 binary
- learning_rate:	0.1	부스팅 스탭 반복할 때 학습률, 0~1 사이의 값
- max_depth	1:	트리의 깊이
- min_data_in_leaf:	20	한 리프의 최소 데이터 수 (decision tree의 min_sample_leaf와 동일, 오버피팅 제어)
- num_leaves:	31	하나의 트리가 가질 수 있는 최대 리프 개수
- boosting	gbdt:	부스팅 방법 (gbdt: Gradient Boosting DecisionTree / rf: RandomForest)
- bagging_fraction:	1.0	데이터 샘플링 비율, 오버피팅 제어
- feature_fraction:	1.0	개별 트리 학습 시 무작위로 선택하는 feature의 비율
- lambda_l1:	0.0	L1 regulation 제어
- lambda_l2:	0.0	L2 regulation 제어
- metric:	""	성능평가를 어떤 것으로 할 것인지 (auc, l1, l2 등)

In [78]:
import lightgbm as lgb

In [79]:
from lightgbm import LGBMRegressor

In [88]:
clf = lgb.LGBMRegressor(num_leaves=31,
                        learning_rate=0.05,
                        n_estimators=20)
clf

LGBMRegressor(learning_rate=0.05, n_estimators=20)

In [150]:
#clf.fit(X_train, y_train, early_stopping_rounds = 1000)
clf.fit(X_train, y_train,
        eval_set=[(X_test, y_test)],
        eval_metric='l2',
        early_stopping_rounds = 100)

[1]	valid_0's l2: 4.99795e+07
[2]	valid_0's l2: 4.61243e+07
[3]	valid_0's l2: 4.26605e+07
[4]	valid_0's l2: 3.94907e+07
[5]	valid_0's l2: 3.66427e+07
[6]	valid_0's l2: 3.40174e+07
[7]	valid_0's l2: 3.16653e+07
[8]	valid_0's l2: 2.94628e+07
[9]	valid_0's l2: 2.74577e+07
[10]	valid_0's l2: 2.56709e+07
[11]	valid_0's l2: 2.40209e+07
[12]	valid_0's l2: 2.25351e+07
[13]	valid_0's l2: 2.11763e+07
[14]	valid_0's l2: 1.99424e+07
[15]	valid_0's l2: 1.8736e+07
[16]	valid_0's l2: 1.76851e+07
[17]	valid_0's l2: 1.66769e+07
[18]	valid_0's l2: 1.57934e+07
[19]	valid_0's l2: 1.49984e+07
[20]	valid_0's l2: 1.42092e+07

C:\Users\admin\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\admin\anaconda3\lib\site-packages\lightgbm\sklearn.py:726: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
C:\Users\admin\anaconda3\lib\site-packages\lightgbm\basic.py:179: UserWarning: Converting column-vector to 1d array
  _log_warning('Converting column-vector to 1d array')

LGBMRegressor(learning_rate=0.05, n_estimators=20)

In [151]:
y_pred = clf.predict(X_test, num_iteration=clf.best_iteration_)

In [152]:
y_pred

array([18848.91715768, 16593.99520976, 18576.7815442 , ...,
       11555.70706028, 13728.1349289 , 18831.56418861])

In [153]:
from sklearn.metrics import mean_absolute_error

In [154]:
print('The rmse of prediction is:', mean_absolute_error(y_test, y_pred))

The rmse of prediction is: 2911.332174181416

In [155]:
print('test accuracy : ', format(clf.score(X_test, y_test))) # 결정계수
print('test accuracy : ', format(r2_score(y_test, clf.predict(X_test)))) # 결정계수

test accuracy :  0.7380640715320048
test accuracy :  0.7380640715320048

# xgb

In [27]:
# 순수 xgboost 스타일 
import xgboost as xgb

# 사이킷런 스타일로 Wrapping된 클레스
# 생성 -> fit() -> predict() -> 평가도구를 활용하여 판단
from xgboost import XGBClassifier

xgb.__version__

'1.6.0'

In [30]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((43130, 151), (14377, 151), (43130, 1), (14377, 1))

In [32]:
car.shape

(57507, 151)

In [33]:
dtrain = xgb.DMatrix( data=x_train, label=y_train )
dtest  = xgb.DMatrix( data=x_test,  label=y_test  )

In [34]:
# 훈련 작성시 파라미터를 부여하여 처리할수 있다 (알고리즘 생성시에도 세팅 가능함)
params = {
  'objective':'binary:logistic', # 예측된 결과는 2종류 이므로, 바이너리이고 개별 클레스에 대한 확률값
  'eval_metric':'logloss',       # 학습을 언제 마무리 하는가? 그 평가 잣대, 손실함수값을 기준으로 판단
  'max_depth':3,                 # 트리의 깊이 -> 과적합 방지에 대한 옵션
  'eta':0.1,                     # 가중치를 조절하는 기준값, 이값을 기준으로 미세조정하여 가중치 조절
  'early_stopping_rounds':100    # 조기학습종료, 100회를 도달하기전에, 
                                 # 원하는 수준에 도달하고, 더이상 값의 변화가 없다면 조기 학습 종료 
                                 # 해당 조건을 만족못하면 pass
}

In [61]:
evals    = [ (dtrain, 'train'), (dtest, 'eval') ]
'''
  로그
  [라운드] 검증시-logloss 테스트시-logloss
  [0]	train-logloss:0.60924	eval-logloss:0.615431
  ....
'''
xgbModel = xgb.train( params=params, 
           dtrain=dtrain,  
           num_boost_round=400,
           evals = evals
          )

[15:39:23] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.6.0/src/learner.cc:627:
Parameters: { "early_stopping_rounds" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.

XGBoostError: [15:39:23] C:/Users/Administrator/workspace/xgboost-win64_release_1.6.0/src/objective/regression_obj.cu:138: label must be in [0,1] for logistic regression

# 결정트리

In [36]:
# 1. 모듈 가져오기
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [37]:
# 2. 알고리즘 생성
'''
criterion : 규칙 노드는 만드는 판단기준 엔트로피 혹은 지니계수 
            사용하는 기준만 지정, 임계값 접근은 파라미터에서 
            미지원 -> 튜닝 포인트는 엔트로피 혹은 지니 둘중 어느쪽에서 더 성능이 
            나오는지 확인
min_samples_split
min_samples_leaf
max_features
max_depth
max_leaf_nodes
random_state : 알고리즘 생성시 사용하는, 내부에서 사용하는 모든 난수의 씨드 설정
- 고정하면 언제다 동일한 성능을 내는 알고리즘 생성
'''
clf = DecisionTreeClassifier( random_state=0 )
clf

DecisionTreeClassifier(random_state=0)

In [38]:
# 3. 데이터 준비

X_train, X_test, y_train, y_test = train_test_split( x, y, train_size = 0.75, random_state=1 )

X_train.shape, X_test.shape,

((43130, 151), (14377, 151))

In [39]:
# 4. 훈련
clf.fit( X_train, y_train )

DecisionTreeClassifier(random_state=0)

In [40]:
# 5. 예측 및 성능평가
clf.score( X_test, y_test )

0.10078597760311608

# 보팅

In [43]:
# 보팅 구현, 실습 -> 여러 알고리즘, 하드 혹은 소프트 보팅 방식 적용

# 알고리즘 준비
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

# 보팅 
from sklearn.ensemble import VotingClassifier

# 데이터셋
from sklearn.datasets import load_breast_cancer

# 데이터셋 준비(훈련용, 테스트요)
from sklearn.model_selection import train_test_split

# 평가도구
from sklearn.metrics import accuracy_score

# 데이터 처리
import pandas as pd

In [47]:
car = pd.read_csv('./car/car.csv')

In [49]:
car = pd.get_dummies(car, prefix_sep='_', drop_first=True)
car.head()

,year,price,mileage,mpg,engineSize,brand_bmw,brand_cclass,brand_focus,brand_ford,brand_hyundi,...,model_ Yeti Outdoor,model_ Zafira,model_ Zafira Tourer,model_220,transmission_Manual,transmission_Other,transmission_Semi-Auto,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2017,12500,15735,55.4,1.4,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1,2016,11000,29946,55.4,1.4,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,2019,17300,1998,49.6,1.0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,2016,13900,32260,58.9,1.4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,2016,13250,76788,61.4,2.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
car.head()

  brand model  year  price transmission  mileage fuelType   mpg  engineSize
0  audi    A1  2017  12500       Manual    15735   Petrol  55.4         1.4
1  audi    A1  2016  11000       Manual    29946   Petrol  55.4         1.4
2  audi    A3  2019  17300       Manual     1998   Petrol  49.6         1.0
3  audi    A1  2016  13900    Automatic    32260   Petrol  58.9         1.4
4  audi    A6  2016  13250    Automatic    76788   Diesel  61.4         2.0

In [46]:
car.shape

(57507, 151)

In [55]:
# 3. 데이터 준비

X_train, X_test, y_train, y_test = train_test_split( x, y, train_size = 0.75, random_state=1 )

X_train.shape, X_test.shape,

((43130, 151), (14377, 151))

In [56]:
lr_clf  = LogisticRegression()
knn_clf = KNeighborsClassifier( n_neighbors=8 )

In [57]:
# 보팅에 사용할 알고리즘 연결
# soft 방식은 경우 알고리즘의 개수가 짝수개 이여도 동수가 나올 확률은 아주 적다
vo_clf = VotingClassifier( estimators=[ ('LR', lr_clf), ('KNN',knn_clf) ], voting ='soft' )

In [58]:
# 보팅에 사용할 알고리즘 연결
# soft 방식은 경우 알고리즘의 개수가 짝수개 이여도 동수가 나올 확률은 아주 적다
vo_clf = VotingClassifier( estimators=[ ('LR', lr_clf), ('KNN',knn_clf) ], voting ='soft' )

In [60]:
# 예측 (n개의 모델이 학습후 대기중)
y_pred = vo_clf.predict( X_test )

NotFittedError: This VotingClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.